apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uf8mi3e1e-dotnet-basic
  janus-idp.io/tekton: uf8mi3e1e-dotnet-basic
  backstage.io/kubernetes-id: uf8mi3e1e-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uf8mi3e1e-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
